# Basic Site Settings
locale: "en-US"
title: "JunHoo Choi / Personal Website"
title_separator: "-"
name: &name "JunHoo Choi"
description: &description "Undergraduate Researcher and Aspiring Scientist with expertise in Molecular Environmental Biology, laboratory techniques, and a passion for research and mentorship."
url: https://JC248.github.io # Update with your actual GitHub Pages link
baseurl: "" # the subpath of your site
repository: "JC248/JC248.github.io"

# Site Author
author:
  avatar: "profile.png"
  name: "JunHoo Choi"
  pronouns: "he/him"
  bio: "Undergraduate Researcher at UC Berkeley with interests in Molecular Environmental Biology, precision engineering, and mentorship."
  location: "Berkeley, California"
  employer: "University of California, Berkeley"
  uri: # Add a link to your academic page if available
  email: "wnsgn9093@berkeley.edu"

  # Academic websites
  googlescholar: # Add if you have a Google Scholar profile
  orcid: # Add if you have an ORCID
  pubmed: # Add if applicable

  # Repositories and software development
  github: "JC248" # Your GitHub username

  # Social media
  linkedin: "https://www.linkedin.com/in/JunChoi248"
  instagram: # Add your username if desired
  twitter: # Add your username if applicable

# Publication Category
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Additional settings remain unchanged
